# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='阅读日期')),
                ('object_id', models.PositiveIntegerField(verbose_name='阅读ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '阅读记录',
                'verbose_name_plural': '阅读记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('object_id', models.PositiveIntegerField(verbose_name='阅读ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '阅读计数',
                'verbose_name_plural': '阅读计数',
                'ordering': ['-read_num'],
            },
        ),
    ]
