# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
    ]
