# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20180606_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'ordering': ['-date'], 'verbose_name': '阅读记录', 'verbose_name_plural': '阅读记录'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'ordering': ['-read_num'], 'verbose_name': '阅读计数', 'verbose_name_plural': '阅读计数'},
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
