# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20180822_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
