# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0006_auto_20180822_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
