# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0007_auto_20180822_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='time',
            field=models.DateField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
    ]
