# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0008_auto_20180822_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
