# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0009_auto_20180822_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='time',
        ),
    ]
