# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0010_remove_readdetail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='阅读日期'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='阅读ID'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='阅读ID'),
        ),
    ]
