# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, '展示'), (1, '隐藏')], default=0, null=True, verbose_name='是否发表'),
        ),
    ]
