# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-29 11:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180527_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
    ]
