# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180529_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
