# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_read_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_num',
        ),
        migrations.AddField(
            model_name='readnum',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Post'),
        ),
    ]
