# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180530_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='post',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
