# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 08:16
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180606_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
